parameters:
#    parameter_name: value

services:
    app.repository.goal:
        class: Infrastructure\ODM\Repository\GoalsRepository
        arguments: ['@doctrine.odm.mongodb.document_manager']
    app.use_case.add_goal:
        class: Domain\UseCase\AddGoal
        arguments: ['@app.repository.goal']
    app.use_case.remove_goal:
        class: Domain\UseCase\RemoveGoal
        arguments: ['@app.repository.goal']
